### ISSUE TITLE
Clicking nodes sometimes triggers drag movement

### ISSUE THREAD

**Issue by JuliusHenke** [KalkulierbaR/kalkulierbar#13]
Reproduce:
1. Start a calculus proof like https://kbar.app/prop-tableaux
2. Try clicking a node while moving the mouse just slightly
3. The intended click is interpreted as a drag event

I think it would be great to increase the margin unitl a drag on a node is triggered.

**Comment by rec0de** [comment]
Should be fixed now, give it a try. The relevant thresholds are in `components/svg/draggable/index.tsx line 93 & 206` for all non-resolution views and `components/calculus/resolution/node/index.tsx line 125 & 239` for the two resolution views.

**Comment by JuliusHenke** [comment]
Thanks, works good now :)
