### ISSUE TITLE
Add Usage Statistics

### ISSUE THREAD

**Issue by JuliusHenke** [KalkulierbaR/kalkulierbar#8]
It would be cool to have page usage statistics. This could include:
- number of specific page views
- user device type
- user country

@rec0de suggested:
I think it'd be pretty cheap to just add a backend endpoint /stats or something and increment some counters whenever e.g. a proof is started.

**Comment by rec0de** [comment]
I played around with a backend logging approach at 0f472052fc9e6268681bf01f138b5e3d5bced606. There's a couple quirks (stats are not actually written to disk until there's a config change, enabling / disabling a calculus is logged as a page view), but I think those aren't too bad. This way we can log:
- Times the config has been loaded (~ times the page has been loaded)
- Times a proof has been started in a given calculus

each broken down into the running month, the last month with non-zero visits, and all-time - without any additional requests, frontend logic and access to any sensitive information.

**Comment by JuliusHenke** [comment]
This sounds really cool. Maybe you could provide an endpoint for an authorized admin to fetch stats?
If so, we could add a Frontend page with visualizations which can be accessed with a valid admin login. I have time at the end of March to work on KalkulierbaR. 😊

**Comment by rec0de** [comment]
There is a /stats endpoint already, although it's public for now. Not sure if it's worth hiding behind auth, but that's definitely something to consider.

A little frontend thing sounds cool!

**Comment by JuliusHenke** [comment]
Great, I agree. Since we do not collect or provide any sensitive data with the /stats endpoint, it could just be public.
